export const configProps = {
  'px': {
    width: 'width',
    height: 'height',
    lineHeight: 'line-height',
    opacity: 'opacity',
    border: 'border',
    borderRadius: 'border-radius',
    borderColor: 'border-color',
    borderWidth: 'border-width',
    backgroundColor: 'background-color',
    color: 'color',
    fontSize: 'font-size',
    fontFamily: 'font-family',
    fontStyle: 'font-style',
    shadows: 'box-shadow',
    innerShadows: 'inner-shadow'
  },
  'dp': {
    width: 'layout_width',
    height: 'layout_height',
    border: 'border',
    opacity: 'opacity',
    color: 'textColor',
    fontSize: 'textSize',
    fontFamily: 'font-family',
    fontStyle: 'font-style',
    backgroundColor: 'background',
    borderRadius: 'radius',
    borderColor: 'border-color',
    borderWidth: 'border-width',
    shadows: 'box-shadow',
    innerShadows: 'inner-shadow'
  },
  'pt': { // ios
    width: 'width',
    height: 'height',
    opacity: 'opacity',
    border: 'border',
    backgroundColor: 'background-color',
    color: 'text-color',
    fontSize: 'font-size',
    fontFamily: 'font-family',
    fontStyle: 'font-style',
    borderRadius: 'border-radius',
    borderColor: 'border-color',
    borderWidth: 'border-width',
    shadows: 'box-shadow',
    innerShadows: 'inner-shadow'
  }
}
